import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
// IMPORTANT: Adjust this import path to where your autogenerated Opportunity model is located.
// For example: 'package:your_project_name/models/opportunity.dart'
import '../models/opportunity.dart'; // <--- VERIFY AND ADJUST THIS IMPORT PATH

import '../services/opportunityService.dart';

class PostOpportunityPage extends StatefulWidget {
  const PostOpportunityPage({super.key});

  @override
  State<PostOpportunityPage> createState() => _PostOpportunityPageState();
}

class _PostOpportunityPageState extends State<PostOpportunityPage> {
  final _formKey = GlobalKey<FormState>();
  final OpportunityService _opportunityService = OpportunityService();

  // Controllers
  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _roleController = TextEditingController();
  final TextEditingController _descriptionController = TextEditingController();
  final TextEditingController _opportunityDatesController =
      TextEditingController();
  final TextEditingController _applicationDatesController =
      TextEditingController();
  final TextEditingController _responseWeeksController =
      TextEditingController();
  final TextEditingController _responseDaysController = TextEditingController();
  final TextEditingController _durationController = TextEditingController();
  final TextEditingController _skillController = TextEditingController();
  final TextEditingController _requirementController = TextEditingController();
  final TextEditingController _otherMajorController = TextEditingController();

  // State variables
  String? _selectedWorkMode;
  String? _selectedLocation;
  String? _displayMajor; // To hold the value for the dropdown display
  String? _selectedMajor;
  String? _selectedType;
  bool _isPaid = true;
  bool _isResponseDateVisible = true;
  bool _isLoading = false;

  DateTime? _startDate;
  DateTime? _endDate;
  DateTime? _applicationOpenDate;
  DateTime? _applicationDeadline;
  DateTime? _calculatedResponseDate; // To show the calculated date in real-time

  final List<String> _selectedSkills = [];
  final List<String> _selectedRequirements = [];

  static const int _maxSkills = 10;
  static const int _maxRequirements = 10;

  // Dropdown options
  final List<String> _workModes = ['In-person', 'Remote', 'Hybrid'];
  final List<String> _saudiCities = [
    'Riyadh',
    'Makkah',
    'Medina',
    'Qassim',
    'Eastern Province',
    'Asir',
    'Tabuk',
    'Northern Borders',
    'Hail',
    'Bahah',
    'Najran',
    'Jazan',
    'Al Jouf',
  ];

  final List<String> _opportunityTypes = [
    'Internship',
    'Co-op',
    'Graduate Program',
    'Bootcamp',
  ];

  List<String> _majorsList = [];
  bool _majorsLoading = true;
  late Future<void> _loadMajorsFuture;

  // Color constants
  static const Color primaryColor = Color(0xFF422F5D);
  static const Color secondaryColor = Color(0xFFF99D46);
  static const Color backgroundColor = Color(0xFFF7F4F0);
  static const Color accentColor = Color(0xFFD64483);

  @override
  void initState() {
    super.initState();
    _loadMajorsFuture = _loadMajors();
    // Add listeners to update the calculated response date in real-time
    _responseWeeksController.addListener(_updateAndDisplayResponseDate);
    _responseDaysController.addListener(_updateAndDisplayResponseDate);
  }

  Future<void> _loadMajors() async {
    try {
      final doc = await FirebaseFirestore.instance
          .collection('lists')
          .doc('majors')
          .get();

      if (doc.exists && mounted) {
        final data = doc.data();
        setState(() {
          _majorsList = [...List<String>.from(data?['names'] ?? []), 'Other'];
          _majorsLoading = false;
        });
      }
    } catch (e) {
      debugPrint('Error loading majors: $e');
    }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _roleController.dispose();
    _descriptionController.dispose();
    _opportunityDatesController.dispose();
    _applicationDatesController.dispose();
    _responseWeeksController.dispose();
    _responseDaysController.dispose();
    _durationController.dispose();
    _skillController.dispose();
    _requirementController.dispose();
    _otherMajorController.dispose();
    super.dispose();
  }

  void _calculateDuration() {
    if (_startDate != null && _endDate != null) {
      final difference = _endDate!.difference(_startDate!).inDays;
      final months = (difference / 30).floor();
      final days = difference % 30;

      String durationText = '';
      if (months > 0) durationText += '$months month${months > 1 ? 's' : ''}';
      if (days > 0) {
        if (durationText.isNotEmpty) durationText += ' ';
        durationText += '$days day${days > 1 ? 's' : ''}';
      }

      setState(() {
        _durationController.text = durationText.isNotEmpty
            ? durationText
            : '0 days';
      });
    }
  }

  Future<void> _postOpportunity() async {
    if (_formKey.currentState!.validate()) {
      setState(() => _isLoading = true);

      final User? currentUser = FirebaseAuth.instance.currentUser;
      if (currentUser == null) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('You must be logged in to post an opportunity.'),
            ),
          );
        }
        return;
      }

      final String companyAuthUid = currentUser.uid;

      // If 'Other' was selected, use the text from the manual input field.
      // Otherwise, use the major selected from the list.
      final String? finalMajor = _selectedMajor == 'Other'
          ? _otherMajorController.text.trim()
          : _displayMajor;

      final Opportunity newOpportunity = Opportunity(
        id: '',
        companyId: companyAuthUid,
        name: _nameController.text.trim(), //
        preferredMajor: finalMajor,
        role: _roleController.text.trim(),
        isPaid: _isPaid,
        type: _selectedType ?? 'Internship',
        workMode: _selectedWorkMode,
        description: _descriptionController.text.trim().isNotEmpty
            ? _descriptionController.text.trim()
            : null,
        requirements: _selectedRequirements.isNotEmpty
            ? _selectedRequirements
            : null,
        skills: _selectedSkills.isNotEmpty ? _selectedSkills : null,
        location:
            (_selectedWorkMode == 'In-person' || _selectedWorkMode == 'Hybrid')
            ? _selectedLocation
            : _selectedWorkMode, // Store 'Remote' or 'Hybrid'
        startDate: _startDate != null ? Timestamp.fromDate(_startDate!) : null,
        endDate: _endDate != null ? Timestamp.fromDate(_endDate!) : null,
        applicationOpenDate: _applicationOpenDate != null
            ? Timestamp.fromDate(_applicationOpenDate!)
            : null,
        applicationDeadline: _applicationDeadline != null
            ? Timestamp.fromDate(_applicationDeadline!)
            : null,
        responseDeadline: _calculateResponseDeadline(),
        postedDate:
            null, // This is null because the service sets the server timestamp.
        isActive: true,
      );

      try {
        await _opportunityService.addOpportunity(newOpportunity);

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Opportunity posted successfully!')),
          );
          Navigator.pop(context);
        }
      } catch (e) {
        debugPrint('Error posting opportunity: $e');
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Failed to post opportunity: $e')),
          );
        }
      } finally {
        if (mounted) setState(() => _isLoading = false);
      }
    }
  }

  Timestamp? _calculateResponseDeadline() {
    if (!_isResponseDateVisible || _applicationDeadline == null) {
      return null;
    }

    final weeks = int.tryParse(_responseWeeksController.text.trim()) ?? 0;
    final days = int.tryParse(_responseDaysController.text.trim()) ?? 0;

    if (weeks == 0 && days == 0) {
      return null; // No duration entered, so no deadline.
    }

    final totalDays = (weeks * 7) + days;
    final calculatedDate = _applicationDeadline!.add(Duration(days: totalDays));
    return Timestamp.fromDate(calculatedDate);
  }

  void _updateAndDisplayResponseDate() {
    if (!_isResponseDateVisible || _applicationDeadline == null) {
      setState(() => _calculatedResponseDate = null);
      return;
    }

    final weeks = int.tryParse(_responseWeeksController.text.trim()) ?? 0;
    final days = int.tryParse(_responseDaysController.text.trim()) ?? 0;

    if (weeks == 0 && days == 0) {
      setState(() => _calculatedResponseDate = null);
      return;
    }

    final totalDays = (weeks * 7) + days;
    final calculatedDate = _applicationDeadline!.add(Duration(days: totalDays));

    // Update the state to rebuild the UI and show the new date
    setState(() => _calculatedResponseDate = calculatedDate);
  }

  void _addSkill() {
    if (_selectedSkills.length >= _maxSkills) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('You can add a maximum of $_maxSkills skills.')),
      );
      return;
    }

    final skill = _skillController.text.trim();
    if (skill.isEmpty) return;

    // Case-insensitive check for duplicates
    final isDuplicate = _selectedSkills.any(
      (s) => s.toLowerCase() == skill.toLowerCase(),
    );

    if (isDuplicate) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('This skill has already been added.')),
      );
      return;
    }

    setState(() {
      _selectedSkills.add(skill);
      _skillController.clear();
    });
  }

  void _removeSkill(String skill) {
    setState(() => _selectedSkills.remove(skill));
  }

  void _addRequirement() {
    if (_selectedRequirements.length >= _maxRequirements) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            'You can add a maximum of $_maxRequirements requirements.',
          ),
        ),
      );
      return;
    }

    final requirement = _requirementController.text.trim();
    if (requirement.isEmpty) return;

    // Case-insensitive check for duplicates
    final isDuplicate = _selectedRequirements.any(
      (r) => r.toLowerCase() == requirement.toLowerCase(),
    );

    if (isDuplicate) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('This requirement has already been added.'),
        ),
      );
      return;
    }

    setState(() {
      _selectedRequirements.add(requirement);
      _requirementController.clear();
    });
  }

  void _removeRequirement(String requirement) {
    setState(() {
      _selectedRequirements.remove(requirement);
    });
  }

  Future<void> _showSearchDialog({
    required BuildContext context,
    required List<String> items,
    required String title,
    required Function(String) onItemSelected,
  }) async {
    final TextEditingController searchController = TextEditingController();
    List<String> filteredItems = List.from(items);

    await showDialog(
      context: context,
      builder: (context) {
        return StatefulBuilder(
          builder: (context, setDialogState) {
            return AlertDialog(
              backgroundColor: backgroundColor,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(20),
              ),
              title: Text(
                'Select $title',
                style: const TextStyle(
                  color: primaryColor,
                  fontWeight: FontWeight.bold,
                ),
              ),
              content: SizedBox(
                width: double.maxFinite,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    TextField(
                      controller: searchController,
                      autofocus: true,
                      decoration: InputDecoration(
                        hintText: 'Search for a $title...',
                        prefixIcon: const Icon(
                          Icons.search,
                          color: primaryColor,
                        ),
                        filled: true,
                        fillColor: Colors.white,
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(12),
                          borderSide: BorderSide.none,
                        ),
                        focusedBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(12),
                          borderSide: const BorderSide(color: primaryColor),
                        ),
                      ),
                      onChanged: (value) {
                        setDialogState(() {
                          filteredItems = items
                              .where(
                                (item) => item.toLowerCase().contains(
                                  value.toLowerCase(),
                                ),
                              )
                              .toList();
                        });
                      },
                    ),
                    const SizedBox(height: 10),
                    Expanded(
                      child: ListView.builder(
                        shrinkWrap: true,
                        itemCount: filteredItems.length,
                        itemBuilder: (context, index) {
                          final item = filteredItems[index];
                          return ListTile(
                            title: Text(
                              item,
                              style: const TextStyle(color: Colors.black87),
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(8),
                            ),
                            onTap: () {
                              onItemSelected(item);
                              Navigator.of(context).pop();
                            },
                          );
                        },
                      ),
                    ),
                  ],
                ),
              ),
              actions: [
                TextButton(
                  onPressed: () => Navigator.of(context).pop(),
                  child: const Text(
                    'Close',
                    style: TextStyle(
                      color: secondaryColor,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ],
            );
          },
        );
      },
    );
  }

  // Helper for consistent styled text form fields
  Widget _buildStyledTextFormField({
    required TextEditingController controller,
    required String labelText,
    String? Function(String?)? validator,
    int maxLines = 1,
    TextInputType keyboardType = TextInputType.text,
    IconData? icon,
    int? maxLength,
    List<TextInputFormatter>? inputFormatters,
    bool readOnly = false,
    VoidCallback? onTap,
    ValueChanged<String>? onFieldSubmitted,
    Widget? suffixIcon,
  }) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8.0),
      child: TextFormField(
        controller: controller,
        decoration: _buildInputDecoration(
          labelText,
          icon: icon,
        ).copyWith(suffixIcon: suffixIcon),
        validator: validator,
        maxLines: maxLines,
        keyboardType: keyboardType,
        inputFormatters: inputFormatters,
        maxLength: maxLength,
        readOnly: readOnly,
        onTap: onTap,
        onFieldSubmitted: onFieldSubmitted,
        autovalidateMode: AutovalidateMode.onUserInteraction,
      ),
    );
  }

  // Helper function to show a single date picker
  Future<DateTime?> _selectDate(
    BuildContext context, {
    DateTime? initialDate,
    DateTime? firstDate,
    DateTime? lastDate,
  }) async {
    return await showDatePicker(
      context: context,
      initialDate: initialDate ?? DateTime.now(),
      firstDate: firstDate ?? DateTime(2024),
      lastDate: lastDate ?? DateTime(2030),
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: const ColorScheme.light(
              primary: primaryColor,
              onPrimary: Colors.white, // Header text color
              onSurface: Colors.black,
            ),
            textButtonTheme: TextButtonThemeData(
              style: TextButton.styleFrom(foregroundColor: secondaryColor),
            ),
          ),
          child: child!,
        );
      },
    );
  }

  // Helper function to show a date range picker
  Future<DateTimeRange?> _selectDateRange(
    BuildContext context, {
    DateTimeRange? initialDateRange,
    DateTime? firstDate,
    DateTime? lastDate,
  }) async {
    return await showDateRangePicker(
      context: context,
      initialDateRange: initialDateRange,
      firstDate: firstDate ?? DateTime(2024),
      lastDate: lastDate ?? DateTime(2030),
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: const ColorScheme.light(
              primary: primaryColor,
              onPrimary: Colors.white,
              onSurface: Colors.black,
            ),
            textButtonTheme: TextButtonThemeData(
              style: TextButton.styleFrom(foregroundColor: secondaryColor),
            ),
          ),
          child: child!,
        );
      },
    );
  }

  void _handleOpportunityDateSelection(DateTimeRange? pickedRange) {
    if (pickedRange == null) return;

    setState(() {
      _startDate = pickedRange.start;
      _endDate = pickedRange.end;
      final format = DateFormat('MMM d, yyyy');
      _opportunityDatesController.text =
          '${format.format(_startDate!)} - ${format.format(_endDate!)}';
      _calculateDuration();

      // --- CONSTRAINTS CHECK ---
      // Application period must be before the new start date.
      if (_applicationDeadline != null &&
          !_applicationDeadline!.isBefore(_startDate!)) {
        _applicationOpenDate = null;
      }
    });
  }

  void _handleApplicationDateSelection(DateTimeRange? pickedRange) {
    if (pickedRange == null) return;

    setState(() {
      _applicationOpenDate = pickedRange.start;
      _applicationDeadline = pickedRange.end;
      final format = DateFormat('MMM d, yyyy');
      _updateAndDisplayResponseDate(); // Recalculate response date
      _applicationDatesController.text =
          '${format.format(_applicationOpenDate!)} - ${format.format(_applicationDeadline!)}';
    });
  }

  @override
  Widget build(BuildContext context) {
    final today = DateUtils.dateOnly(DateTime.now());
    return Scaffold(
      backgroundColor: backgroundColor,
      appBar: AppBar(
        title: const Text(
          'Post New Opportunity',
          style: TextStyle(color: primaryColor, fontWeight: FontWeight.bold),
        ),
        backgroundColor: backgroundColor,
        iconTheme: const IconThemeData(color: primaryColor),
        elevation: 0,
      ),
      body: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(20),
          child: Form(
            key: _formKey,
            child: Column(
              children: [
                // Opportunity Name
                _buildStyledTextFormField(
                  controller: _nameController,
                  labelText: 'Opportunity Name',
                  icon: Icons.work_outline,
                  inputFormatters: [LengthLimitingTextInputFormatter(50)],
                  validator: (value) {
                    if (value == null || value.isEmpty)
                      return 'Please enter opportunity name';
                    if (value.length > 50) return 'Cannot exceed 50 characters';
                    return null;
                  },
                ),

                // Role
                _buildStyledTextFormField(
                  controller: _roleController,
                  labelText: 'Role',
                  icon: Icons.badge_outlined,
                  inputFormatters: [LengthLimitingTextInputFormatter(40)],
                  validator: (value) {
                    if (value == null || value.isEmpty)
                      return 'Please enter the role';
                    if (value.length > 40) return 'Cannot exceed 40 characters';
                    return null;
                  },
                ),

                // Preferred Major
                _buildSearchableDropdown(
                  labelText: 'Preferred Major',
                  // Use the displayMajor for the UI
                  selectedValue: _displayMajor,
                  icon: Icons.book_outlined,
                  validator: _majorsLoading
                      ? null
                      : (value) {
                          if (_selectedMajor == null)
                            if (_selectedMajor == null) {
                              return 'Please select a major';
                            }
                          if (_selectedMajor == 'Other' &&
                              _otherMajorController.text.trim().isEmpty) {
                            return 'Please specify the major';
                          }
                          return null;
                        },
                  onTap: _majorsLoading
                      ? null // Disable tap while loading
                      : () async {
                          await _showSearchDialog(
                            context: context,
                            items: _majorsList, // This now includes "Other"
                            title: 'Major',
                            onItemSelected: (value) {
                              setState(() {
                                _selectedMajor =
                                    value; // This tracks the actual selection
                                _displayMajor = (value == 'Other')
                                    ? null
                                    : value; // This is for display
                                if (value != 'Other') {
                                  _otherMajorController.clear();
                                }
                              });
                            },
                          );
                        },
                  enabled: !_majorsLoading,
                ),
                if (_selectedMajor == 'Other')
                  _buildStyledTextFormField(
                    controller: _otherMajorController,
                    labelText: 'Please specify the major',
                    icon: Icons.edit_note_outlined,
                    inputFormatters: [LengthLimitingTextInputFormatter(40)],
                    validator: (v) {
                      if (_selectedMajor == 'Other' &&
                          (v == null || v.trim().isEmpty))
                        return 'This field is required';
                      return null;
                    },
                  ),

                // Description
                _buildStyledTextFormField(
                  controller: _descriptionController,
                  labelText: 'Description',
                  icon: Icons.description_outlined,
                  maxLength: 500,
                  maxLines: 4,
                  keyboardType: TextInputType.multiline,
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'Please enter a description';
                    }
                    return null;
                  },
                ),

                // Work Mode
                _buildDropdownFormField(
                  labelText: 'Work Mode',
                  items: _workModes,
                  selectedValue: _selectedWorkMode,
                  onChanged: (value) {
                    setState(() {
                      _selectedWorkMode = value;
                      if (value == 'Remote') _selectedLocation = null;
                    });
                  },
                  icon: Icons.location_city_outlined,
                  validator: (value) =>
                      value == null ? 'Please select work mode' : null,
                ),

                // Location (only for In-person or Hybrid)
                if (_selectedWorkMode == 'In-person' ||
                    _selectedWorkMode == 'Hybrid')
                  _buildDropdownFormField(
                    labelText: 'Location',
                    items: _saudiCities,
                    selectedValue: _selectedLocation,
                    onChanged: (value) =>
                        setState(() => _selectedLocation = value),
                    icon: Icons.location_on_outlined,
                    validator: (value) =>
                        value == null ? 'Please select a location' : null,
                  ),

                // Skills
                _buildStyledTextFormField(
                  controller: _skillController,
                  labelText: 'Add Required Skills',
                  icon: Icons.lightbulb_outline,
                  onFieldSubmitted: (value) => _addSkill(),
                  inputFormatters: [LengthLimitingTextInputFormatter(30)],
                  suffixIcon: IconButton(
                    icon: const Icon(Icons.add_circle, color: Colors.blue),
                    onPressed: _addSkill,
                  ),
                ),
                if (_selectedSkills.isNotEmpty)
                  Wrap(
                    spacing: 8.0,
                    children: _selectedSkills
                        .map(
                          (skill) => Chip(
                            label: Text(skill),
                            backgroundColor: secondaryColor.withOpacity(0.8),
                            labelStyle: const TextStyle(color: Colors.white),
                            onDeleted: () => _removeSkill(skill),
                            deleteIconColor: Colors.white,
                          ),
                        )
                        .toList(),
                  ),

                const SizedBox(height: 8),

                // Requirements
                _buildStyledTextFormField(
                  controller: _requirementController,
                  labelText: 'Add Requirements',
                  icon: Icons.checklist_outlined,
                  onFieldSubmitted: (value) => _addRequirement(),
                  inputFormatters: [LengthLimitingTextInputFormatter(100)],
                  suffixIcon: IconButton(
                    icon: const Icon(Icons.add_circle, color: Colors.blue),
                    onPressed: _addRequirement,
                  ),
                ),
                if (_selectedRequirements.isNotEmpty)
                  Wrap(
                    spacing: 8.0,
                    children: _selectedRequirements
                        .map(
                          (req) => Chip(
                            label: Text(req),
                            backgroundColor: accentColor.withOpacity(0.8),
                            labelStyle: const TextStyle(color: Colors.white),
                            onDeleted: () => _removeRequirement(req),
                            deleteIconColor: Colors.white,
                          ),
                        )
                        .toList(),
                  ),

                const SizedBox(height: 8),

                // Opportunity Type
                _buildDropdownFormField(
                  labelText: 'Opportunity Type',
                  items: _opportunityTypes,
                  selectedValue: _opportunityTypes.contains(_selectedType)
                      ? _selectedType
                      : null,
                  onChanged: (value) => setState(() => _selectedType = value),
                  icon: Icons.category_outlined,
                  validator: (value) => value == null || value.isEmpty
                      ? 'Please select opportunity type'
                      : null,
                ),

                // Is Paid Toggle
                Container(
                  margin: const EdgeInsets.symmetric(vertical: 8.0),
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      const Text(
                        'Paid Opportunity?',
                        style: TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      Switch(
                        value: _isPaid,
                        onChanged: (value) => setState(() => _isPaid = value),
                        activeColor: accentColor,
                      ),
                    ],
                  ),
                ),

                // Opportunity Dates (Start & End)
                _buildStyledTextFormField(
                  controller: _opportunityDatesController,
                  labelText: 'Opportunity Duration (Start - End)',
                  icon: Icons.calendar_today,
                  readOnly: true,
                  onTap: () async {
                    final pickedRange = await _selectDateRange(
                      context,
                      firstDate: today,
                      initialDateRange: (_startDate != null && _endDate != null)
                          ? DateTimeRange(start: _startDate!, end: _endDate!)
                          : null,
                    );
                    _handleOpportunityDateSelection(pickedRange);
                  },
                  validator: (value) => value == null || value.isEmpty
                      ? 'Please select opportunity start and end dates'
                      : null,
                ),

                // Application Dates (Begins & Deadline)
                _buildStyledTextFormField(
                  controller: _applicationDatesController,
                  labelText: 'Application Period (Begins - Deadline)',
                  icon: Icons.calendar_month,
                  readOnly: true,
                  onTap: _startDate == null
                      ? () {
                          ScaffoldMessenger.of(context).showSnackBar(
                            const SnackBar(
                              content: Text(
                                'Please select the opportunity duration first.',
                              ),
                            ),
                          );
                        }
                      : () async {
                          final pickedRange = await _selectDateRange(
                            context,
                            firstDate: today,
                            lastDate: _startDate!.subtract(
                              const Duration(days: 1),
                            ),
                            initialDateRange:
                                (_applicationOpenDate != null &&
                                    _applicationDeadline != null)
                                ? DateTimeRange(
                                    start: _applicationOpenDate!,
                                    end: _applicationDeadline!,
                                  )
                                : null,
                          );
                          _handleApplicationDateSelection(pickedRange);
                        },
                  validator: (value) => value == null || value.isEmpty
                      ? 'Please select the application period'
                      : null,
                ),

                // Duration (Auto-calculated)
                _buildStyledTextFormField(
                  controller: _durationController,
                  labelText: 'Duration (Auto-calculated)',
                  icon: Icons.timelapse,
                  readOnly: true,
                ),

                // Response Date Visibility Toggle
                Container(
                  margin: const EdgeInsets.symmetric(vertical: 8.0),
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      const Text(
                        'Make Response Date Visible to Students?',
                        style: TextStyle(
                          fontSize: 14,
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      Switch(
                        value: _isResponseDateVisible,
                        onChanged: (value) =>
                            setState(() => _isResponseDateVisible = value),
                        activeColor: accentColor,
                      ),
                    ],
                  ),
                ),

                // Response Date (Now conditional)
                if (_isResponseDateVisible)
                  Column(
                    children: [
                      Padding(
                        padding: const EdgeInsets.symmetric(vertical: 8.0),
                        child: Row(
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            // Weeks Input
                            SizedBox(
                              width: 70,
                              child: TextFormField(
                                controller: _responseWeeksController,
                                decoration: _buildInputDecoration('').copyWith(
                                  prefixIcon: const Icon(
                                    Icons.notifications_active_outlined,
                                    color: Colors.grey,
                                  ),
                                ),
                                keyboardType: TextInputType.number,
                                inputFormatters: [
                                  FilteringTextInputFormatter.digitsOnly,
                                ],
                                textAlign: TextAlign.center,
                                validator: (value) {
                                  final calculatedDeadline =
                                      _calculateResponseDeadline()?.toDate();
                                  if (calculatedDeadline != null &&
                                      _startDate != null &&
                                      !calculatedDeadline.isBefore(
                                        _startDate!,
                                      )) {
                                    return 'Must be before start date!!';
                                  }
                                  return null;
                                },
                                autovalidateMode:
                                    AutovalidateMode.onUserInteraction,
                              ),
                            ),
                            const Padding(
                              padding: EdgeInsets.only(left: 8.0, right: 12.0),
                              child: Text('weeks and'),
                            ),
                            const SizedBox(width: 10),
                            // Days Input
                            SizedBox(
                              width: 70,
                              child: TextFormField(
                                controller: _responseDaysController,
                                decoration: _buildInputDecoration(''),
                                keyboardType: TextInputType.number,
                                inputFormatters: [
                                  FilteringTextInputFormatter.digitsOnly,
                                ],
                                textAlign: TextAlign.center,
                                autovalidateMode:
                                    AutovalidateMode.onUserInteraction,
                              ),
                            ),
                            const Expanded(
                              child: Padding(
                                padding: EdgeInsets.only(left: 8.0),
                                child: Text('days after deadline'),
                              ),
                            ),
                          ],
                        ),
                      ),
                      if (_calculatedResponseDate != null)
                        Padding(
                          padding: const EdgeInsets.only(top: 4, bottom: 8),
                          child: Text(
                            'Expected Response By: ${DateFormat('MMMM dd, yyyy').format(_calculatedResponseDate!)}',
                            style: TextStyle(
                              color: primaryColor.withOpacity(0.8),
                              fontWeight: FontWeight.w500,
                            ),
                          ),
                        ),
                    ],
                  ),

                const SizedBox(height: 30),

                // Post Opportunity Button
                _buildGradientButton(
                  text: 'Post Opportunity',
                  onPressed: _postOpportunity,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  // Helper for consistent InputDecorations
  InputDecoration _buildInputDecoration(
    String labelText, {
    IconData? icon,
    bool enabled = true,
  }) {
    return InputDecoration(
      labelText: labelText,
      labelStyle: TextStyle(color: enabled ? primaryColor : Colors.grey),
      prefixIcon: icon != null
          ? Icon(icon, color: enabled ? Colors.grey : Colors.grey.shade300)
          : null,
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: const BorderSide(color: primaryColor),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: const BorderSide(color: accentColor, width: 2),
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: BorderSide(
          color: enabled ? const Color(0x80422F5D) : Colors.grey.shade300,
        ),
      ),
      filled: true,
      fillColor: enabled ? Colors.white : Colors.grey.shade100,
    );
  }

  Widget _buildSearchableDropdown({
    required String labelText,
    required String? selectedValue,
    required IconData icon,
    required VoidCallback? onTap,
    bool enabled = true,
    String? Function(String?)?
    validator, // This validator will check the text field's value
  }) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8.0),
      child: TextFormField(
        controller: TextEditingController(
          text: selectedValue ?? (_majorsLoading ? 'Loading majors...' : ''),
        ),
        readOnly: true,
        onTap: onTap,
        validator: validator,
        decoration: _buildInputDecoration(labelText).copyWith(
          prefixIcon: Icon(icon, color: Colors.grey),
          suffixIcon: const Icon(Icons.arrow_drop_down, color: primaryColor),
        ),
        enabled: enabled,
      ),
    );
  }

  Widget _buildDropdownFormField({
    required String labelText,
    required List<String> items,
    required String? selectedValue,
    required void Function(String?) onChanged,
    required IconData icon,
    String? Function(String?)? validator,
  }) {
    return Container(
      margin: const EdgeInsets.symmetric(vertical: 8.0),
      child: DropdownButtonFormField<String>(
        value: selectedValue,
        onChanged: onChanged,
        validator: validator,
        dropdownColor: backgroundColor,
        menuMaxHeight: 250,
        icon: const Icon(Icons.arrow_drop_down, color: primaryColor),
        decoration: _buildInputDecoration(
          labelText,
        ).copyWith(prefixIcon: Icon(icon, color: Colors.grey)),
        items: items.map<DropdownMenuItem<String>>((String value) {
          return DropdownMenuItem<String>(
            value: value,
            child: Text(
              value,
              style: const TextStyle(color: primaryColor, fontSize: 14),
              overflow: TextOverflow.ellipsis,
            ),
          );
        }).toList(),
      ),
    );
  }

  Widget _buildGradientButton({
    required String text,
    required VoidCallback onPressed,
  }) {
    return SizedBox(
      width: double.infinity,
      child: DecoratedBox(
        decoration: BoxDecoration(
          gradient: const LinearGradient(
            colors: [secondaryColor, accentColor],
            begin: Alignment.centerLeft,
            end: Alignment.centerRight,
          ),
          borderRadius: BorderRadius.circular(30),
        ),
        child: ElevatedButton(
          onPressed: _isLoading ? null : onPressed,
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.transparent,
            shadowColor: Colors.transparent,
            padding: const EdgeInsets.symmetric(vertical: 18),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(30),
            ),
          ),
          child: _isLoading
              ? const CircularProgressIndicator(color: Colors.white)
              : Text(
                  text,
                  style: const TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                    color: Colors.white,
                  ),
                ),
        ),
      ),
    );
  }
}