import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
// IMPORTANT: Adjust this import path to where your autogenerated Opportunity model is located.
// For example: 'package:your_project_name/models/opportunity.dart'
import '../models/opportunity.dart'; // <--- VERIFY AND ADJUST THIS IMPORT PATH

import '../services/opportunityService.dart';

class PostOpportunityPage extends StatefulWidget {
  const PostOpportunityPage({super.key});

  @override
  State<PostOpportunityPage> createState() => _PostOpportunityPageState();
}

class _PostOpportunityPageState extends State<PostOpportunityPage> {
  final _formKey = GlobalKey<FormState>();
  final OpportunityService _opportunityService = OpportunityService();

  // Controllers
  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _roleController = TextEditingController();
  final TextEditingController _descriptionController = TextEditingController();
  final TextEditingController _opportunityDatesController =
      TextEditingController();
  final TextEditingController _applicationDatesController =
      TextEditingController();
  final TextEditingController _durationController = TextEditingController();
  final TextEditingController _skillController = TextEditingController();
  final TextEditingController _requirementController = TextEditingController();
  final TextEditingController _otherMajorController = TextEditingController();

  // State variables
  String? _selectedWorkMode;
  String? _selectedLocation;
  String? _displayMajor; // To hold the value for the dropdown display
  String? _selectedMajor;
  String? _selectedType;
  bool _isPaid = true; // Default to paid
  bool _isLoading = false;
  bool _nameAtLimit = false;
  bool _roleAtLimit = false;
  bool _nameHasInvalidChars = false;
  bool _roleHasInvalidChars = false;

  DateTime? _startDate;
  DateTime? _endDate;
  DateTime? _applicationOpenDate;
  DateTime? _applicationDeadline;
  DateTime? _responseDeadline;
  bool _responseDeadlineVisible =
      false; // Whether students can see the response deadline
  // final TextEditingController _responseDeadlineController =
  //     TextEditingController();

  final List<String> _selectedSkills = [];
  final List<String> _selectedRequirements = [];

  static const int _maxSkills = 10;
  static const int _maxRequirements = 10;
  static const int _nameMaxLength = 50;
  static const int _roleMaxLength = 40;
  static final RegExp _lettersRegExp = RegExp(r'^[A-Za-z ]+$');

  // Dropdown options
  final List<String> _workModes = ['In-person', 'Remote', 'Hybrid'];
  final List<String> _saudiCities = [
    'Riyadh',
    'Makkah',
    'Medina',
    'Qassim',
    'Eastern Province',
    'Asir',
    'Tabuk',
    'Northern Borders',
    'Hail',
    'Bahah',
    'Najran',
    'Jazan',
    'Al Jouf',
  ];

  final List<String> _opportunityTypes = [
    'Internship',
    'Co-op',
    'Graduate Program',
    'Bootcamp',
  ];

  List<String> _majorsList = [];
  bool _majorsLoading = true;
  late Future<void> _loadMajorsFuture;

  // Color constants
  static const Color primaryColor = Color(0xFF422F5D);
  static const Color secondaryColor = Color(0xFFF99D46);
  static const Color backgroundColor = Color(0xFFF7F4F0);
  static const Color accentColor = Color(0xFFD64483);

  @override
  void initState() {
    super.initState();
    _loadMajorsFuture = _loadMajors();
  }

  Future<void> _loadMajors() async {
    try {
      final doc = await FirebaseFirestore.instance
          .collection('lists')
          .doc('majors')
          .get();

      if (doc.exists && mounted) {
        final data = doc.data();
        setState(() {
          _majorsList = [...List<String>.from(data?['names'] ?? []), 'Other'];
          _majorsLoading = false;
        });
      }
    } catch (e) {
      debugPrint('Error loading majors: $e');
    }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _roleController.dispose();
    _descriptionController.dispose();
    _opportunityDatesController.dispose();
    _applicationDatesController.dispose();
    _durationController.dispose();
    _skillController.dispose();
    _requirementController.dispose();
    _otherMajorController.dispose();
    // _responseDeadlineController.dispose();
    super.dispose();
  }

  void _handleNameLength() {
    final text = _nameController.text;
    final atLimit = text.length >= _nameMaxLength;
    final hasInvalid =
        text.trim().isNotEmpty && !_lettersRegExp.hasMatch(text.trim());
    if (mounted &&
        (_nameAtLimit != atLimit || _nameHasInvalidChars != hasInvalid)) {
      setState(() {
        _nameAtLimit = atLimit;
        _nameHasInvalidChars = hasInvalid;
      });
    }
  }

  void _handleRoleLength() {
    final text = _roleController.text;
    final atLimit = text.length >= _roleMaxLength;
    final hasInvalid =
        text.trim().isNotEmpty && !_lettersRegExp.hasMatch(text.trim());
    if (mounted &&
        (_roleAtLimit != atLimit || _roleHasInvalidChars != hasInvalid)) {
      setState(() {
        _roleAtLimit = atLimit;
        _roleHasInvalidChars = hasInvalid;
      });
    }
  }

  void _calculateDuration() {
    if (_startDate != null && _endDate != null) {
      final difference = _endDate!.difference(_startDate!).inDays;
      final months = (difference / 30).floor();
      final days = difference % 30;

      String durationText = '';
      if (months > 0) durationText += '$months month${months > 1 ? 's' : ''}';
      if (days > 0) {
        if (durationText.isNotEmpty) durationText += ' ';
        durationText += '$days day${days > 1 ? 's' : ''}';
      }

      setState(() {
        _durationController.text = durationText.isNotEmpty
            ? durationText
            : '0 days';
      });
    }
  }

  Future<void> _postOpportunity() async {
    if (_formKey.currentState!.validate()) {
      // Final validation: ensure response deadline (if provided) is after applicationDeadline
      // and before opportunity start date
      if (_responseDeadline != null) {
        if (_applicationDeadline != null &&
            !_responseDeadline!.isAfter(_applicationDeadline!)) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text(
                'Response deadline must be after the application deadline.',
              ),
            ),
          );
          return;
        }
        if (_startDate != null && !_responseDeadline!.isBefore(_startDate!)) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text(
                'Response deadline must be before the opportunity start date.',
              ),
            ),
          );
          return;
        }
      }

      setState(() => _isLoading = true);

      final User? currentUser = FirebaseAuth.instance.currentUser;
      if (currentUser == null) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('You must be logged in to post an opportunity.'),
            ),
          );
        }
        return;
      }

      final String companyAuthUid = currentUser.uid;

      final String? finalMajor = _selectedMajor == 'Other'
          ? _otherMajorController.text.trim()
          : _displayMajor;

      final Opportunity newOpportunity = Opportunity(
        id: '',
        companyId: companyAuthUid,
        name: _nameController.text.trim(),
        preferredMajor: finalMajor,
        role: _roleController.text.trim(),
        isPaid: _isPaid,
        type: _selectedType ?? 'Internship',
        workMode: _selectedWorkMode,
        description: _descriptionController.text.trim().isNotEmpty
            ? _descriptionController.text.trim()
            : null,
        requirements: _selectedRequirements.isNotEmpty
            ? _selectedRequirements
            : null,
        skills: _selectedSkills.isNotEmpty ? _selectedSkills : null,
        location:
            (_selectedWorkMode == 'In-person' || _selectedWorkMode == 'Hybrid')
            ? _selectedLocation
            : _selectedWorkMode,
        startDate: _startDate != null ? Timestamp.fromDate(_startDate!) : null,
        endDate: _endDate != null ? Timestamp.fromDate(_endDate!) : null,
        applicationOpenDate: _applicationOpenDate != null
            ? Timestamp.fromDate(_applicationOpenDate!)
            : null,
        applicationDeadline: _applicationDeadline != null
            ? Timestamp.fromDate(_applicationDeadline!)
            : null,
        responseDeadline: _responseDeadline != null
            ? Timestamp.fromDate(_responseDeadline!)
            : null,
        responseDeadlineVisible: _responseDeadlineVisible,
        postedDate: null,
        isActive: true,
      );

      try {
        await _opportunityService.addOpportunity(newOpportunity);

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Opportunity posted successfully!')),
          );
          Navigator.pop(context);
        }
      } catch (e) {
        debugPrint('Error posting opportunity: $e');
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Failed to post opportunity: $e')),
          );
        }
      } finally {
        if (mounted) setState(() => _isLoading = false);
      }
    }
  }

  void _addSkill() {
    if (_selectedSkills.length >= _maxSkills) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('You can add a maximum of $_maxSkills skills.')),
      );
      return;
    }

    final skill = _skillController.text.trim();
    if (skill.isEmpty) return;

    final isDuplicate = _selectedSkills.any(
      (s) => s.toLowerCase() == skill.toLowerCase(),
    );

    if (isDuplicate) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('This skill has already been added.')),
      );
      return;
    }

    setState(() {
      _selectedSkills.add(skill);
      _skillController.clear();
    });
  }

  void _removeSkill(String skill) {
    setState(() => _selectedSkills.remove(skill));
  }

  void _addRequirement() {
    if (_selectedRequirements.length >= _maxRequirements) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            'You can add a maximum of $_maxRequirements requirements.',
          ),
        ),
      );
      return;
    }

    final requirement = _requirementController.text.trim();
    if (requirement.isEmpty) return;

    final isDuplicate = _selectedRequirements.any(
      (r) => r.toLowerCase() == requirement.toLowerCase(),
    );

    if (isDuplicate) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('This requirement has already been added.'),
        ),
      );
      return;
    }

    setState(() {
      _selectedRequirements.add(requirement);
      _requirementController.clear();
    });
  }

  void _removeRequirement(String requirement) {
    setState(() {
      _selectedRequirements.remove(requirement);
    });
  }

  Future<void> _showSearchDialog({
    required BuildContext context,
    required List<String> items,
    required String title,
    required Function(String) onItemSelected,
  }) async {
    final TextEditingController searchController = TextEditingController();
    List<String> filteredItems = List.from(items);

    await showDialog(
      context: context,
      builder: (context) {
        return StatefulBuilder(
          builder: (context, setDialogState) {
            return AlertDialog(
              backgroundColor: backgroundColor,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(20),
              ),
              title: Text(
                'Select $title',
                style: const TextStyle(
                  color: primaryColor,
                  fontWeight: FontWeight.bold,
                ),
              ),
              content: SizedBox(
                width: double.maxFinite,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    TextField(
                      controller: searchController,
                      autofocus: true,
                      decoration: InputDecoration(
                        hintText: 'Search for a $title...',
                        prefixIcon: const Icon(
                          Icons.search,
                          color: primaryColor,
                        ),
                        filled: true,
                        fillColor: Colors.white,
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(12),
                          borderSide: BorderSide.none,
                        ),
                        focusedBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(12),
                          borderSide: const BorderSide(color: primaryColor),
                        ),
                      ),
                      onChanged: (value) {
                        setDialogState(() {
                          filteredItems = items
                              .where(
                                (item) => item.toLowerCase().contains(
                                  value.toLowerCase(),
                                ),
                              )
                              .toList();
                        });
                      },
                    ),
                    const SizedBox(height: 10),
                    Expanded(
                      child: ListView.builder(
                        shrinkWrap: true,
                        itemCount: filteredItems.length,
                        itemBuilder: (context, index) {
                          final item = filteredItems[index];
                          return ListTile(
                            title: Text(
                              item,
                              style: const TextStyle(color: Colors.black87),
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(8),
                            ),
                            onTap: () {
                              onItemSelected(item);
                              Navigator.of(context).pop();
                            },
                          );
                        },
                      ),
                    ),
                  ],
                ),
              ),
              actions: [
                TextButton(
                  onPressed: () => Navigator.of(context).pop(),
                  child: const Text(
                    'Close',
                    style: TextStyle(
                      color: secondaryColor,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ],
            );
          },
        );
      },
    );
  }

  Widget _buildStyledTextFormField({
    required TextEditingController controller,
    required String labelText,
    String? Function(String?)? validator,
    int maxLines = 1,
    TextInputType keyboardType = TextInputType.text,
    TextInputAction? textInputAction,
    IconData? icon,
    int? maxLength,
    List<TextInputFormatter>? inputFormatters,
    bool readOnly = false,
    bool enabled = true,
    VoidCallback? onTap,
    ValueChanged<String>? onFieldSubmitted,
    ValueChanged<String>? onChanged,
    Widget? suffixIcon,
    bool showLabelAbove = false,
    String? hintText,
  }) {
    final field = TextFormField(
      controller: controller,
      enabled: enabled,
      decoration: _buildInputDecoration(
        showLabelAbove ? null : labelText,
        icon: icon,
        enabled: enabled,
        hintText: hintText,
      ).copyWith(suffixIcon: suffixIcon),
      validator: validator,
      maxLines: maxLines,
      keyboardType: keyboardType,
      textInputAction: textInputAction,
      inputFormatters: inputFormatters,
      maxLength: maxLength,
      readOnly: readOnly,
      onTap: onTap,
      onFieldSubmitted: onFieldSubmitted,
      onChanged: onChanged,
      autovalidateMode: AutovalidateMode.onUserInteraction,
    );

    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          if (showLabelAbove) ...[
            Text(
              labelText,
              style: const TextStyle(
                fontSize: 14,
                fontWeight: FontWeight.w600,
                color: primaryColor,
              ),
            ),
            const SizedBox(height: 6),
          ],
          field,
        ],
      ),
    );
  }

  Future<DateTime?> _selectDate(
    BuildContext context, {
    DateTime? initialDate,
    DateTime? firstDate,
    DateTime? lastDate,
  }) async {
    return await showDatePicker(
      context: context,
      initialDate: initialDate ?? DateTime.now(),
      firstDate: firstDate ?? DateTime(2000),
      lastDate: lastDate ?? DateTime(2100),
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: const ColorScheme.light(
              primary: primaryColor,
              onPrimary: Colors.white,
              onSurface: Colors.black,
            ),
            textButtonTheme: TextButtonThemeData(
              style: TextButton.styleFrom(foregroundColor: secondaryColor),
            ),
          ),
          child: child!,
        );
      },
    );
  }

  Future<DateTimeRange?> _selectDateRange(
    BuildContext context, {
    DateTimeRange? initialDateRange,
    DateTime? firstDate,
    DateTime? lastDate,
  }) async {
    return await showDateRangePicker(
      context: context,
      initialDateRange: initialDateRange,
      firstDate: firstDate ?? DateTime(2000),
      lastDate: lastDate ?? DateTime(2100),
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: const ColorScheme.light(
              primary: primaryColor,
              onPrimary: Colors.white,
              onSurface: Colors.black,
            ),
            textButtonTheme: TextButtonThemeData(
              style: TextButton.styleFrom(foregroundColor: secondaryColor),
            ),
          ),
          child: child!,
        );
      },
    );
  }

  void _handleOpportunityDateSelection(DateTimeRange? pickedRange) {
    if (pickedRange == null) return;

    setState(() {
      _startDate = pickedRange.start;
      _endDate = pickedRange.end;
      final format = DateFormat('MMM d, yyyy');
      _opportunityDatesController.text =
          '${format.format(_startDate!)} - ${format.format(_endDate!)}';
      _calculateDuration();
    });
    _formKey.currentState?.validate();
  }

  void _handleApplicationDateSelection(DateTimeRange? pickedRange) {
    if (pickedRange == null) return;

    setState(() {
      _applicationOpenDate = pickedRange.start;
      _applicationDeadline = pickedRange.end;
      final format = DateFormat('MMM d, yyyy');
      _applicationDatesController.text =
          '${format.format(_applicationOpenDate!)} - ${format.format(_applicationDeadline!)}';
    });
    _formKey.currentState?.validate();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: backgroundColor,
      appBar: AppBar(
        title: const Text(
          'Post New Opportunity',
          style: TextStyle(color: primaryColor, fontWeight: FontWeight.bold),
        ),
        backgroundColor: backgroundColor,
        iconTheme: const IconThemeData(color: primaryColor),
        elevation: 0,
      ),
      body: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(20),
          child: Form(
            key: _formKey,
            child: Column(
              children: [
                _buildStyledTextFormField(
                  controller: _nameController,
                  labelText: 'Opportunity Name',
                  icon: Icons.work_outline,
                  maxLength: _nameMaxLength,
                  inputFormatters: [
                    LengthLimitingTextInputFormatter(_nameMaxLength),
                  ],
                  onChanged: (_) => _handleNameLength(),
                  validator: (value) {
                    final trimmed = value?.trim() ?? '';
                    if (trimmed.isEmpty) {
                      return 'Please enter opportunity name';
                    }
                    if (!_lettersRegExp.hasMatch(trimmed)) {
                      return 'Only letters and spaces are allowed';
                    }
                    if (trimmed.length > _nameMaxLength) {
                      return 'Cannot exceed $_nameMaxLength characters';
                    }
                    return null;
                  },
                ),
                if (_nameAtLimit)
                  const Align(
                    alignment: Alignment.centerRight,
                    child: Padding(
                      padding: EdgeInsets.only(bottom: 4),
                      child: Text(
                        'Character limit reached',
                        style: TextStyle(
                          fontSize: 12,
                          color: accentColor,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                  ),
                if (_nameHasInvalidChars)
                  const Align(
                    alignment: Alignment.centerRight,
                    child: Padding(
                      padding: EdgeInsets.only(bottom: 4),
                      child: Text(
                        'Only letters and spaces are allowed',
                        style: TextStyle(
                          fontSize: 12,
                          color: accentColor,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                  ),

                _buildStyledTextFormField(
                  controller: _roleController,
                  labelText: 'Role',
                  icon: Icons.badge_outlined,
                  maxLength: _roleMaxLength,
                  inputFormatters: [
                    LengthLimitingTextInputFormatter(_roleMaxLength),
                  ],
                  onChanged: (_) => _handleRoleLength(),
                  validator: (value) {
                    final trimmed = value?.trim() ?? '';
                    if (trimmed.isEmpty) {
                      return 'Please enter the role';
                    }
                    if (!_lettersRegExp.hasMatch(trimmed)) {
                      return 'Only letters and spaces are allowed';
                    }
                    if (trimmed.length > _roleMaxLength) {
                      return 'Cannot exceed $_roleMaxLength characters';
                    }
                    return null;
                  },
                ),
                if (_roleAtLimit)
                  const Align(
                    alignment: Alignment.centerRight,
                    child: Padding(
                      padding: EdgeInsets.only(bottom: 4),
                      child: Text(
                        'Character limit reached',
                        style: TextStyle(
                          fontSize: 12,
                          color: accentColor,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                  ),
                if (_roleHasInvalidChars)
                  const Align(
                    alignment: Alignment.centerRight,
                    child: Padding(
                      padding: EdgeInsets.only(bottom: 4),
                      child: Text(
                        'Only letters and spaces are allowed',
                        style: TextStyle(
                          fontSize: 12,
                          color: accentColor,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                  ),

                _buildSearchableDropdown(
                  labelText: 'Preferred Major',
                  selectedValue: _displayMajor,
                  icon: Icons.book_outlined,
                  validator: _majorsLoading
                      ? null
                      : (value) {
                          if (_selectedMajor == null)
                            if (_selectedMajor == null) {
                              return 'Please select a major';
                            }
                          if (_selectedMajor == 'Other' &&
                              _otherMajorController.text.trim().isEmpty) {
                            return 'Please specify the major';
                          }
                          return null;
                        },
                  onTap: _majorsLoading
                      ? null
                      : () async {
                          await _showSearchDialog(
                            context: context,
                            items: _majorsList,
                            title: 'Major',
                            onItemSelected: (value) {
                              setState(() {
                                _selectedMajor = value;
                                _displayMajor = (value == 'Other')
                                    ? null
                                    : value;
                                if (value != 'Other') {
                                  _otherMajorController.clear();
                                }
                              });
                            },
                          );
                        },
                  enabled: !_majorsLoading,
                ),
                if (_selectedMajor == 'Other')
                  _buildStyledTextFormField(
                    controller: _otherMajorController,
                    labelText: 'Please specify the major',
                    icon: Icons.edit_note_outlined,
                    inputFormatters: [LengthLimitingTextInputFormatter(40)],
                    validator: (v) {
                      if (_selectedMajor == 'Other' &&
                          (v == null || v.trim().isEmpty))
                        return 'This field is required';
                      return null;
                    },
                  ),

                _buildDescriptionField(),

                _buildDropdownFormField(
                  labelText: 'Work Mode',
                  items: _workModes,
                  selectedValue: _selectedWorkMode,
                  onChanged: (value) {
                    setState(() {
                      _selectedWorkMode = value;
                      if (value == 'Remote') _selectedLocation = null;
                    });
                  },
                  icon: Icons.location_city_outlined,
                  validator: (value) =>
                      value == null ? 'Please select work mode' : null,
                ),

                if (_selectedWorkMode == 'In-person' ||
                    _selectedWorkMode == 'Hybrid')
                  _buildDropdownFormField(
                    labelText: 'Location',
                    items: _saudiCities,
                    selectedValue: _selectedLocation,
                    onChanged: (value) =>
                        setState(() => _selectedLocation = value),
                    icon: Icons.location_on_outlined,
                    validator: (value) =>
                        value == null ? 'Please select a location' : null,
                  ),

                _buildStyledTextFormField(
                  controller: _skillController,
                  labelText: 'Add Required Skills',
                  icon: Icons.lightbulb_outline,
                  onFieldSubmitted: (value) => _addSkill(),
                  inputFormatters: [LengthLimitingTextInputFormatter(30)],
                  suffixIcon: IconButton(
                    icon: const Icon(Icons.add_circle, color: Colors.blue),
                    onPressed: _addSkill,
                  ),
                ),
                if (_selectedSkills.isNotEmpty)
                  Wrap(
                    spacing: 8.0,
                    runSpacing: 8.0,
                    children: _selectedSkills
                        .map(
                          (skill) => _buildTagChip(
                            context,
                            text: skill,
                            background: secondaryColor.withOpacity(0.15),
                            borderColor: secondaryColor.withOpacity(0.3),
                            textColor: secondaryColor,
                            iconColor: secondaryColor,
                            onRemove: () => _removeSkill(skill),
                          ),
                        )
                        .toList(),
                  ),

                const SizedBox(height: 8),

                _buildStyledTextFormField(
                  controller: _requirementController,
                  labelText: 'Add Requirements',
                  icon: Icons.checklist_outlined,
                  onFieldSubmitted: (value) => _addRequirement(),
                  inputFormatters: [LengthLimitingTextInputFormatter(100)],
                  suffixIcon: IconButton(
                    icon: const Icon(Icons.add_circle, color: Colors.blue),
                    onPressed: _addRequirement,
                  ),
                ),
                if (_selectedRequirements.isNotEmpty)
                  Wrap(
                    spacing: 8.0,
                    runSpacing: 8.0,
                    children: _selectedRequirements
                        .map(
                          (req) => _buildTagChip(
                            context,
                            text: req,
                            background: accentColor.withOpacity(0.15),
                            borderColor: accentColor.withOpacity(0.3),
                            textColor: accentColor,
                            iconColor: accentColor,
                            onRemove: () => _removeRequirement(req),
                          ),
                        )
                        .toList(),
                  ),

                const SizedBox(height: 8),

                _buildDropdownFormField(
                  labelText: 'Opportunity Type',
                  items: _opportunityTypes,
                  selectedValue: _opportunityTypes.contains(_selectedType)
                      ? _selectedType
                      : null,
                  onChanged: (value) => setState(() => _selectedType = value),
                  icon: Icons.category_outlined,
                  validator: (value) => value == null || value.isEmpty
                      ? 'Please select opportunity type'
                      : null,
                ),

                Container(
                  margin: const EdgeInsets.symmetric(vertical: 8.0),
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      const Text(
                        'Paid Opportunity?',
                        style: TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      Switch(
                        value: _isPaid,
                        onChanged: (value) => setState(() => _isPaid = value),
                        activeColor: accentColor,
                      ),
                    ],
                  ),
                ),

                _buildStyledTextFormField(
                  controller: _opportunityDatesController,
                  labelText: 'Opportunity Duration (Start - End)',
                  icon: Icons.calendar_today,
                  readOnly: true,
                  onTap: () async {
                    final pickedRange = await _selectDateRange(
                      context,
                      initialDateRange: (_startDate != null && _endDate != null)
                          ? DateTimeRange(start: _startDate!, end: _endDate!)
                          : null,
                      firstDate: DateTime.now(),
                    );
                    _handleOpportunityDateSelection(pickedRange);
                  },
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'Please select opportunity start and end dates';
                    }
                    return null;
                  },
                ),

                _buildStyledTextFormField(
                  controller: _applicationDatesController,
                  labelText: 'Application Period (Begins - Deadline)',
                  icon: Icons.calendar_month,
                  readOnly: true,
                  onTap: () async {
                    final pickedRange = await _selectDateRange(
                      context,
                      initialDateRange:
                          (_applicationOpenDate != null &&
                              _applicationDeadline != null)
                          ? DateTimeRange(
                              start: _applicationOpenDate!,
                              end: _applicationDeadline!,
                            )
                          : null,
                      firstDate: DateTime.now(),
                    );
                    _handleApplicationDateSelection(pickedRange);
                  },
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'Please select the application period';
                    }
                    if (_applicationDeadline != null && _startDate != null) {
                      if (!_applicationDeadline!.isBefore(_startDate!)) {
                        return 'Application deadline must be before the opportunity starts';
                      }
                    }
                    return null;
                  },
                ),

                // Response deadline (optional) + visibility toggle
                _buildStyledTextFormField(
                  controller: TextEditingController(
                    text: _responseDeadline != null
                        ? DateFormat('MMM d, yyyy').format(_responseDeadline!)
                        : '',
                  ),
                  labelText:
                      'Response Deadline (Company must update applicant statuses by)',
                  icon: Icons.event_available,
                  readOnly: true,
                  onTap: () async {
                    DateTime? minDate = _applicationDeadline;
                    DateTime? maxDate = _startDate;
                    final pickedDate = await _selectDate(
                      context,
                      initialDate:
                          _responseDeadline ??
                          (minDate != null
                              ? minDate.add(const Duration(days: 1))
                              : DateTime.now()),
                      firstDate: minDate != null
                          ? minDate.add(const Duration(days: 1))
                          : DateTime.now(),
                      lastDate: maxDate != null
                          ? maxDate.subtract(const Duration(days: 1))
                          : DateTime(2100),
                    );
                    if (pickedDate != null) {
                      setState(() {
                        _responseDeadline = pickedDate;
                      });
                    }
                  },
                  validator: (value) {
                    if (_responseDeadline == null) {
                      return 'Please select a response deadline';
                    }
                    if (_applicationDeadline != null &&
                        _responseDeadline!.isBefore(
                          _applicationDeadline!.add(const Duration(days: 1)),
                        )) {
                      return 'Response deadline must be after application deadline';
                    }
                    if (_startDate != null &&
                        _responseDeadline!.isAfter(
                          _startDate!.subtract(const Duration(days: 1)),
                        )) {
                      return 'Response deadline must be before opportunity start date';
                    }
                    return null;
                  },
                ),

                Container(
                  margin: const EdgeInsets.symmetric(vertical: 8.0),
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      const Expanded(
                        child: Text(
                          'Show response deadline to students?',
                          style: TextStyle(
                            fontSize: 15,
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Switch(
                        value: _responseDeadlineVisible,
                        onChanged: (v) =>
                            setState(() => _responseDeadlineVisible = v),
                        activeColor: accentColor,
                      ),
                    ],
                  ),
                ),

                _buildStyledTextFormField(
                  controller: _durationController,
                  labelText: 'Duration of the Opportunity',
                  icon: Icons.timelapse,
                  readOnly: true,
                  enabled: false,
                  showLabelAbove: true,
                  hintText: 'Auto-calculated',
                ),

                const SizedBox(height: 30),

                _buildGradientButton(
                  text: 'Post Opportunity',
                  onPressed: _postOpportunity,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  // MODIFIED: Helper widget for the description field with a bottom-right button
  Widget _buildDescriptionField() {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8.0),
      child: Stack(
        children: [
          TextFormField(
            controller: _descriptionController,
            decoration: _buildInputDecoration(
              'Description',
              icon: Icons.description_outlined,
            ),
            maxLength: 500,
            maxLines: 4,
            keyboardType: TextInputType.multiline,
            validator: (value) {
              if (value == null || value.isEmpty) {
                return 'Please enter a description';
              }
              return null;
            },
            autovalidateMode: AutovalidateMode.onUserInteraction,
          ),
          Positioned(
            bottom: 28.0, // Positioned just above the counter text
            right: 8.0,
            child: ElevatedButton(
              onPressed: () {
                FocusScope.of(context).unfocus(); // Dismiss the keyboard
              },
              style: ElevatedButton.styleFrom(
                backgroundColor: primaryColor.withOpacity(0.8),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(20),
                ),
                padding: const EdgeInsets.symmetric(
                  horizontal: 16,
                  vertical: 4,
                ),
                minimumSize: Size.zero, // Make it compact
              ),
              child: const Text(
                'Done',
                style: TextStyle(color: Colors.white, fontSize: 12),
              ),
            ),
          ),
        ],
      ),
    );
  }

  InputDecoration _buildInputDecoration(
    String? labelText, {
    IconData? icon,
    bool enabled = true,
    String? hintText,
  }) {
    return InputDecoration(
      labelText: labelText,
      labelStyle: labelText != null
          ? TextStyle(color: enabled ? primaryColor : Colors.grey)
          : null,
      hintText: hintText,
      hintStyle: TextStyle(
        color: Colors.grey.shade500,
        fontSize: 13,
        fontStyle: FontStyle.italic,
      ),
      prefixIcon: icon != null
          ? Icon(icon, color: enabled ? Colors.grey : Colors.grey.shade300)
          : null,
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: const BorderSide(color: primaryColor),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: const BorderSide(color: accentColor, width: 2),
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: BorderSide(
          color: enabled ? const Color(0x80422F5D) : Colors.grey.shade300,
        ),
      ),
      filled: true,
      fillColor: enabled ? Colors.white : Colors.grey.shade100,
    );
  }

  Widget _buildSearchableDropdown({
    required String labelText,
    required String? selectedValue,
    required IconData icon,
    required VoidCallback? onTap,
    bool enabled = true,
    String? Function(String?)? validator,
  }) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8.0),
      child: TextFormField(
        controller: TextEditingController(
          text: selectedValue ?? (_majorsLoading ? 'Loading majors...' : ''),
        ),
        readOnly: true,
        onTap: onTap,
        validator: validator,
        decoration: _buildInputDecoration(labelText, enabled: enabled).copyWith(
          prefixIcon: Icon(icon, color: Colors.grey),
          suffixIcon: const Icon(Icons.arrow_drop_down, color: primaryColor),
        ),
        enabled: enabled,
      ),
    );
  }

  Widget _buildDropdownFormField({
    required String labelText,
    required List<String> items,
    required String? selectedValue,
    required void Function(String?) onChanged,
    required IconData icon,
    String? Function(String?)? validator,
  }) {
    return Container(
      margin: const EdgeInsets.symmetric(vertical: 8.0),
      child: DropdownButtonFormField<String>(
        value: selectedValue,
        onChanged: onChanged,
        validator: validator,
        dropdownColor: backgroundColor,
        menuMaxHeight: 250,
        icon: const Icon(Icons.arrow_drop_down, color: primaryColor),
        decoration: _buildInputDecoration(
          labelText,
        ).copyWith(prefixIcon: Icon(icon, color: Colors.grey)),
        items: items.map<DropdownMenuItem<String>>((String value) {
          return DropdownMenuItem<String>(
            value: value,
            child: Text(
              value,
              style: const TextStyle(color: primaryColor, fontSize: 14),
              overflow: TextOverflow.ellipsis,
            ),
          );
        }).toList(),
      ),
    );
  }

  Widget _buildTagChip(
    BuildContext context, {
    required String text,
    required Color background,
    required Color textColor,
    Color? iconColor,
    Color? borderColor,
    VoidCallback? onRemove,
  }) {
    final maxWidth = MediaQuery.of(context).size.width - 80;
    return ConstrainedBox(
      constraints: BoxConstraints(
        maxWidth: maxWidth > 0 ? maxWidth : double.infinity,
      ),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
        decoration: BoxDecoration(
          color: background,
          borderRadius: BorderRadius.circular(20),
          border: borderColor != null ? Border.all(color: borderColor) : null,
        ),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Expanded(
              child: Text(
                text,
                style: TextStyle(
                  fontSize: 13,
                  fontWeight: FontWeight.w600,
                  color: textColor,
                ),
                softWrap: true,
              ),
            ),
            if (onRemove != null) ...[
              const SizedBox(width: 8),
              InkWell(
                onTap: onRemove,
                child: Icon(
                  Icons.close,
                  size: 18,
                  color: iconColor ?? textColor,
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildGradientButton({
    required String text,
    required VoidCallback onPressed,
  }) {
    return SizedBox(
      width: double.infinity,
      child: DecoratedBox(
        decoration: BoxDecoration(
          gradient: const LinearGradient(
            colors: [secondaryColor, accentColor],
            begin: Alignment.centerLeft,
            end: Alignment.centerRight,
          ),
          borderRadius: BorderRadius.circular(30),
        ),
        child: ElevatedButton(
          onPressed: _isLoading ? null : onPressed,
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.transparent,
            shadowColor: Colors.transparent,
            padding: const EdgeInsets.symmetric(vertical: 18),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(30),
            ),
          ),
          child: _isLoading
              ? const CircularProgressIndicator(color: Colors.white)
              : Text(
                  text,
                  style: const TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                    color: Colors.white,
                  ),
                ),
        ),
      ),
    );
  }
}
