// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVQMxrZ2kDXXBvL7XIuRXgIg4B6JdjqVk',
    appId: '1:911829965377:android:b78ebf7cc969c8264184c0',
    messagingSenderId: '911829965377',
    projectId: 'spark-22564',
    storageBucket: 'spark-22564.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMm-CMAOB127oBzdg7BNGtS2q2KuwjuNA',
    appId: '1:911829965377:ios:4f511ca13081cd6a4184c0',
    messagingSenderId: '911829965377',
    projectId: 'spark-22564',
    storageBucket: 'spark-22564.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoJ-f3vB3N3ZK1z37dIMwAjNdbg6muDc8',
    appId: '1:911829965377:web:3178cfe2d5f656214184c0',
    messagingSenderId: '911829965377',
    projectId: 'spark-22564',
    authDomain: 'spark-22564.firebaseapp.com',
    storageBucket: 'spark-22564.firebasestorage.app',
    measurementId: 'G-J7BRF5FTQC',
  );

}